#############################################################################
# Makefile for building: final.app/Contents/MacOS/final
# Generated by qmake (2.01a) (Qt 4.8.1) on: Wed Mar 27 10:53:40 2013
# Project:  testbed.pro
# Template: app
# Command: /Users/parker/QtSDK/Desktop/Qt/4.8.1/gcc/bin/qmake -spec ../../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/macx-g++ CONFIG+=x86_64 CONFIG+=declarative_debug -o Makefile testbed.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_OPENGL_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -g -gdwarf-2 -arch x86_64 -Xarch_x86_64 -mmacosx-version-min=10.7 -Wall -W $(DEFINES)
CXXFLAGS      = -pipe -g -gdwarf-2 -arch x86_64 -Xarch_x86_64 -mmacosx-version-min=10.7 -Wall -W $(DEFINES)
INCPATH       = -I../../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/macx-g++ -I. -I../../../../QtSDK/Desktop/Qt/4.8.1/gcc/lib/QtCore.framework/Versions/4/Headers -I../../../../QtSDK/Desktop/Qt/4.8.1/gcc/include/QtCore -I../../../../QtSDK/Desktop/Qt/4.8.1/gcc/lib/QtGui.framework/Versions/4/Headers -I../../../../QtSDK/Desktop/Qt/4.8.1/gcc/include/QtGui -I../../../../QtSDK/Desktop/Qt/4.8.1/gcc/lib/QtOpenGL.framework/Versions/4/Headers -I../../../../QtSDK/Desktop/Qt/4.8.1/gcc/include/QtOpenGL -I../../../../QtSDK/Desktop/Qt/4.8.1/gcc/include -Imain -Ilib -Imath -Igeom -Isupport -I/System/Library/Frameworks/OpenGL.framework/Versions/A/Headers -I/System/Library/Frameworks/AGL.framework/Headers -I. -I. -F/Users/parker/QtSDK/Desktop/Qt/4.8.1/gcc/lib
LINK          = g++
LFLAGS        = -headerpad_max_install_names -arch x86_64 -Xarch_x86_64 -mmacosx-version-min=10.7
LIBS          = $(SUBLIBS) -F/Users/parker/QtSDK/Desktop/Qt/4.8.1/gcc/lib -L/Users/parker/QtSDK/Desktop/Qt/4.8.1/gcc/lib -framework QtOpenGL -L/usr/local/pgsql/lib -L/tmp/qt-stuff-85167/source/qt-everywhere-opensource-src-4.8.1/Desktop/Qt/4.8.1/gcc/lib -F/tmp/qt-stuff-85167/source/qt-everywhere-opensource-src-4.8.1/Desktop/Qt/4.8.1/gcc/lib -framework QtGui -framework QtCore -framework OpenGL -framework AGL 
AR            = ar cq
RANLIB        = ranlib -s
QMAKE         = /Users/parker/QtSDK/Desktop/Qt/4.8.1/gcc/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
STRIP         = 
INSTALL_FILE  = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = $(COPY_FILE)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
export MACOSX_DEPLOYMENT_TARGET = 10.4

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main/glwidget.cpp \
		support/mainwindow.cpp \
		support/main.cpp \
		math/CS123Matrix.cpp \
		lib/utils.cpp \
		support/OrbitingCamera.cpp \
		support/mouseinput.cpp \
		geom/polygon.cpp \
		geom/edge.cpp \
		geom/vertex.cpp \
		geom/mesh.cpp \
		geom/material.cpp \
		math/ray.cpp \
		geom/triangle.cpp \
		main/geomInteraction.cpp \
		tools/manipulator.cpp moc_glwidget.cpp \
		moc_mainwindow.cpp
OBJECTS       = glwidget.o \
		mainwindow.o \
		main.o \
		CS123Matrix.o \
		utils.o \
		OrbitingCamera.o \
		mouseinput.o \
		polygon.o \
		edge.o \
		vertex.o \
		mesh.o \
		material.o \
		ray.o \
		triangle.o \
		geomInteraction.o \
		manipulator.o \
		moc_glwidget.o \
		moc_mainwindow.o
DIST          = ../../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/unix.conf \
		../../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/mac.conf \
		../../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/gcc-base.conf \
		../../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/gcc-base-macx.conf \
		../../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/g++-base.conf \
		../../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/g++-macx.conf \
		../../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/qconfig.pri \
		../../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/modules/qt_webkit_version.pri \
		../../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/qt_functions.prf \
		../../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/qt_config.prf \
		../../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/exclusive_builds.prf \
		../../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/default_pre.prf \
		../../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/mac/default_pre.prf \
		../../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/mac/dwarf2.prf \
		../../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/debug.prf \
		../../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/default_post.prf \
		../../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/mac/default_post.prf \
		../../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/mac/x86_64.prf \
		../../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/mac/objective_c.prf \
		../../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/declarative_debug.prf \
		../../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/warn_on.prf \
		../../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/qt.prf \
		../../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/unix/opengl.prf \
		../../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/unix/thread.prf \
		../../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/moc.prf \
		../../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/mac/rez.prf \
		../../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/mac/sdk.prf \
		../../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/resources.prf \
		../../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/uic.prf \
		../../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/yacc.prf \
		../../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/lex.prf \
		../../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/include_source_dir.prf \
		testbed.pro
QMAKE_TARGET  = final
DESTDIR       = 
TARGET        = final.app/Contents/MacOS/final

####### Custom Compiler Variables
QMAKE_COMP_QMAKE_OBJECTIVE_CFLAGS = -pipe \
		-g \
		-arch \
		x86_64 \
		-Xarch_x86_64 \
		-mmacosx-version-min=10.7 \
		-Wall \
		-W


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile final.app/Contents/PkgInfo final.app/Contents/Resources/empty.lproj final.app/Contents/Info.plist $(TARGET)

$(TARGET): ui_mainwindow.h $(OBJECTS)  
	@$(CHK_DIR_EXISTS) final.app/Contents/MacOS/ || $(MKDIR) final.app/Contents/MacOS/ 
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: testbed.pro  ../../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/macx-g++/qmake.conf ../../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/unix.conf \
		../../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/mac.conf \
		../../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/gcc-base.conf \
		../../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/gcc-base-macx.conf \
		../../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/g++-base.conf \
		../../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/g++-macx.conf \
		../../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/qconfig.pri \
		../../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/modules/qt_webkit_version.pri \
		../../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/qt_functions.prf \
		../../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/qt_config.prf \
		../../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/exclusive_builds.prf \
		../../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/default_pre.prf \
		../../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/mac/default_pre.prf \
		../../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/mac/dwarf2.prf \
		../../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/debug.prf \
		../../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/default_post.prf \
		../../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/mac/default_post.prf \
		../../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/mac/x86_64.prf \
		../../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/mac/objective_c.prf \
		../../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/declarative_debug.prf \
		../../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/warn_on.prf \
		../../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/qt.prf \
		../../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/unix/opengl.prf \
		../../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/unix/thread.prf \
		../../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/moc.prf \
		../../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/mac/rez.prf \
		../../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/mac/sdk.prf \
		../../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/resources.prf \
		../../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/uic.prf \
		../../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/yacc.prf \
		../../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/lex.prf \
		../../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/include_source_dir.prf \
		/Users/parker/QtSDK/Desktop/Qt/4.8.1/gcc/lib/QtOpenGL.framework/QtOpenGL.prl \
		/Users/parker/QtSDK/Desktop/Qt/4.8.1/gcc/lib/QtGui.framework/QtGui.prl \
		/Users/parker/QtSDK/Desktop/Qt/4.8.1/gcc/lib/QtCore.framework/QtCore.prl
	$(QMAKE) -spec ../../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/macx-g++ CONFIG+=x86_64 CONFIG+=declarative_debug -o Makefile testbed.pro
../../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/unix.conf:
../../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/mac.conf:
../../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/gcc-base.conf:
../../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/gcc-base-macx.conf:
../../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/g++-base.conf:
../../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/g++-macx.conf:
../../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/qconfig.pri:
../../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/modules/qt_webkit_version.pri:
../../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/qt_functions.prf:
../../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/qt_config.prf:
../../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/exclusive_builds.prf:
../../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/default_pre.prf:
../../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/mac/default_pre.prf:
../../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/mac/dwarf2.prf:
../../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/debug.prf:
../../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/default_post.prf:
../../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/mac/default_post.prf:
../../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/mac/x86_64.prf:
../../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/mac/objective_c.prf:
../../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/declarative_debug.prf:
../../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/warn_on.prf:
../../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/qt.prf:
../../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/unix/opengl.prf:
../../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/unix/thread.prf:
../../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/moc.prf:
../../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/mac/rez.prf:
../../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/mac/sdk.prf:
../../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/resources.prf:
../../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/uic.prf:
../../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/yacc.prf:
../../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/lex.prf:
../../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/include_source_dir.prf:
/Users/parker/QtSDK/Desktop/Qt/4.8.1/gcc/lib/QtOpenGL.framework/QtOpenGL.prl:
/Users/parker/QtSDK/Desktop/Qt/4.8.1/gcc/lib/QtGui.framework/QtGui.prl:
/Users/parker/QtSDK/Desktop/Qt/4.8.1/gcc/lib/QtCore.framework/QtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec ../../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/macx-g++ CONFIG+=x86_64 CONFIG+=declarative_debug -o Makefile testbed.pro

final.app/Contents/PkgInfo: 
	@$(CHK_DIR_EXISTS) final.app/Contents || $(MKDIR) final.app/Contents 
	@$(DEL_FILE) final.app/Contents/PkgInfo
	@echo "APPL????" >final.app/Contents/PkgInfo
final.app/Contents/Resources/empty.lproj: 
	@$(CHK_DIR_EXISTS) final.app/Contents/Resources || $(MKDIR) final.app/Contents/Resources 
	@touch final.app/Contents/Resources/empty.lproj
	
final.app/Contents/Info.plist: 
	@$(CHK_DIR_EXISTS) final.app/Contents || $(MKDIR) final.app/Contents 
	@$(DEL_FILE) final.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,@TYPEINFO@,????,g" -e "s,@ICON@,,g" -e "s,@EXECUTABLE@,final,g" -e "s,@TYPEINFO@,????,g" ../../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/macx-g++/Info.plist.app >final.app/Contents/Info.plist
dist: 
	@$(CHK_DIR_EXISTS) .tmp/final1.0.0 || $(MKDIR) .tmp/final1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/final1.0.0/ && $(COPY_FILE) --parents main/glwidget.h support/mainwindow.h main/glwidget.h math/CS123Matrix.h math/CS123Algebra.h math/CS123Vector.h lib/utils.h lib/CS123Common.h support/OrbitingCamera.h support/camera.h lib/aabb.h support/mouseinput.h geom/polygon.h geom/edge.h geom/vertex.h geom/mesh.h geom/material.h math/ray.h geom/triangle.h lib/aabb2D.h tools/manipulator.h .tmp/final1.0.0/ && $(COPY_FILE) --parents main/glwidget.cpp support/mainwindow.cpp support/main.cpp math/CS123Matrix.cpp lib/utils.cpp support/OrbitingCamera.cpp support/mouseinput.cpp geom/polygon.cpp geom/edge.cpp geom/vertex.cpp geom/mesh.cpp geom/material.cpp math/ray.cpp geom/triangle.cpp main/geomInteraction.cpp tools/manipulator.cpp .tmp/final1.0.0/ && $(COPY_FILE) --parents support/mainwindow.ui support/mainwindow.ui .tmp/final1.0.0/ && (cd `dirname .tmp/final1.0.0` && $(TAR) final1.0.0.tar final1.0.0 && $(COMPRESS) final1.0.0.tar) && $(MOVE) `dirname .tmp/final1.0.0`/final1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/final1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) -r final.app
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_objective_c_make_all:
compiler_objective_c_clean:
compiler_moc_header_make_all: moc_glwidget.cpp moc_mainwindow.cpp moc_glwidget.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_glwidget.cpp moc_mainwindow.cpp moc_glwidget.cpp
moc_glwidget.cpp: support/mainwindow.h \
		support/camera.h \
		math/CS123Algebra.h \
		math/CS123Matrix.h \
		math/CS123Vector.h \
		lib/CS123Common.h \
		math/CS123Vector.inl \
		math/CS123Matrix.inl \
		support/OrbitingCamera.h \
		lib/utils.h \
		geom/polygon.h \
		geom/edge.h \
		geom/vertex.h \
		geom/material.h \
		math/ray.h \
		geom/triangle.h \
		main/glwidget.h \
		math/vector.h \
		support/mouseinput.h \
		geom/mesh.h \
		tools/manipulator.h \
		main/glwidget.h
	/Users/parker/QtSDK/Desktop/Qt/4.8.1/gcc/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ main/glwidget.h -o moc_glwidget.cpp

moc_mainwindow.cpp: support/mainwindow.h
	/Users/parker/QtSDK/Desktop/Qt/4.8.1/gcc/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ support/mainwindow.h -o moc_mainwindow.cpp

moc_glwidget.cpp: support/mainwindow.h \
		support/camera.h \
		math/CS123Algebra.h \
		math/CS123Matrix.h \
		math/CS123Vector.h \
		lib/CS123Common.h \
		math/CS123Vector.inl \
		math/CS123Matrix.inl \
		support/OrbitingCamera.h \
		lib/utils.h \
		geom/polygon.h \
		geom/edge.h \
		geom/vertex.h \
		geom/material.h \
		math/ray.h \
		geom/triangle.h \
		main/glwidget.h \
		math/vector.h \
		support/mouseinput.h \
		geom/mesh.h \
		tools/manipulator.h \
		main/glwidget.h
	/Users/parker/QtSDK/Desktop/Qt/4.8.1/gcc/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ main/glwidget.h -o moc_glwidget.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_uic_make_all: ui_mainwindow.h ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h ui_mainwindow.h
ui_mainwindow.h: support/mainwindow.ui \
		main/glwidget.h \
		support/mainwindow.h \
		support/camera.h \
		math/CS123Algebra.h \
		math/CS123Matrix.h \
		math/CS123Vector.h \
		lib/CS123Common.h \
		math/CS123Vector.inl \
		math/CS123Matrix.inl \
		support/OrbitingCamera.h \
		lib/utils.h \
		geom/polygon.h \
		geom/edge.h \
		geom/vertex.h \
		geom/material.h \
		math/ray.h \
		geom/triangle.h \
		main/glwidget.h \
		math/vector.h \
		support/mouseinput.h \
		geom/mesh.h \
		tools/manipulator.h
	/Users/parker/QtSDK/Desktop/Qt/4.8.1/gcc/bin/uic support/mainwindow.ui -o ui_mainwindow.h

ui_mainwindow.h: support/mainwindow.ui \
		main/glwidget.h \
		support/mainwindow.h \
		support/camera.h \
		math/CS123Algebra.h \
		math/CS123Matrix.h \
		math/CS123Vector.h \
		lib/CS123Common.h \
		math/CS123Vector.inl \
		math/CS123Matrix.inl \
		support/OrbitingCamera.h \
		lib/utils.h \
		geom/polygon.h \
		geom/edge.h \
		geom/vertex.h \
		geom/material.h \
		math/ray.h \
		geom/triangle.h \
		main/glwidget.h \
		math/vector.h \
		support/mouseinput.h \
		geom/mesh.h \
		tools/manipulator.h
	/Users/parker/QtSDK/Desktop/Qt/4.8.1/gcc/bin/uic support/mainwindow.ui -o ui_mainwindow.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

glwidget.o: main/glwidget.cpp main/glwidget.h \
		support/mainwindow.h \
		support/camera.h \
		math/CS123Algebra.h \
		math/CS123Matrix.h \
		math/CS123Vector.h \
		lib/CS123Common.h \
		math/CS123Vector.inl \
		math/CS123Matrix.inl \
		support/OrbitingCamera.h \
		lib/utils.h \
		geom/polygon.h \
		geom/edge.h \
		geom/vertex.h \
		geom/material.h \
		math/ray.h \
		geom/triangle.h \
		math/vector.h \
		support/mouseinput.h \
		geom/mesh.h \
		tools/manipulator.h \
		lib/aabb2D.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o glwidget.o main/glwidget.cpp

mainwindow.o: support/mainwindow.cpp support/mainwindow.h \
		ui_mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o support/mainwindow.cpp

main.o: support/main.cpp support/mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o support/main.cpp

CS123Matrix.o: math/CS123Matrix.cpp math/CS123Matrix.h \
		math/CS123Vector.h \
		math/CS123Algebra.h \
		lib/CS123Common.h \
		math/CS123Vector.inl \
		math/CS123Matrix.inl
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o CS123Matrix.o math/CS123Matrix.cpp

utils.o: lib/utils.cpp lib/utils.h \
		support/camera.h \
		math/CS123Algebra.h \
		math/CS123Matrix.h \
		math/CS123Vector.h \
		lib/CS123Common.h \
		math/CS123Vector.inl \
		math/CS123Matrix.inl \
		geom/polygon.h \
		geom/edge.h \
		geom/vertex.h \
		geom/material.h \
		math/ray.h \
		geom/triangle.h \
		main/glwidget.h \
		support/mainwindow.h \
		support/OrbitingCamera.h \
		math/vector.h \
		support/mouseinput.h \
		geom/mesh.h \
		tools/manipulator.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o utils.o lib/utils.cpp

OrbitingCamera.o: support/OrbitingCamera.cpp support/OrbitingCamera.h \
		math/CS123Algebra.h \
		math/CS123Matrix.h \
		math/CS123Vector.h \
		lib/CS123Common.h \
		math/CS123Vector.inl \
		math/CS123Matrix.inl \
		lib/utils.h \
		support/camera.h \
		geom/polygon.h \
		geom/edge.h \
		geom/vertex.h \
		geom/material.h \
		math/ray.h \
		geom/triangle.h \
		main/glwidget.h \
		support/mainwindow.h \
		math/vector.h \
		support/mouseinput.h \
		geom/mesh.h \
		tools/manipulator.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o OrbitingCamera.o support/OrbitingCamera.cpp

mouseinput.o: support/mouseinput.cpp support/mouseinput.h \
		math/CS123Algebra.h \
		math/CS123Matrix.h \
		math/CS123Vector.h \
		lib/CS123Common.h \
		math/CS123Vector.inl \
		math/CS123Matrix.inl
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mouseinput.o support/mouseinput.cpp

polygon.o: geom/polygon.cpp geom/polygon.h \
		math/CS123Algebra.h \
		math/CS123Matrix.h \
		math/CS123Vector.h \
		lib/CS123Common.h \
		math/CS123Vector.inl \
		math/CS123Matrix.inl \
		geom/edge.h \
		geom/vertex.h \
		geom/material.h \
		math/ray.h \
		geom/triangle.h \
		lib/utils.h \
		support/camera.h \
		main/glwidget.h \
		support/mainwindow.h \
		support/OrbitingCamera.h \
		math/vector.h \
		support/mouseinput.h \
		geom/mesh.h \
		tools/manipulator.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o polygon.o geom/polygon.cpp

edge.o: geom/edge.cpp geom/edge.h \
		geom/vertex.h \
		geom/polygon.h \
		math/CS123Algebra.h \
		math/CS123Matrix.h \
		math/CS123Vector.h \
		lib/CS123Common.h \
		math/CS123Vector.inl \
		math/CS123Matrix.inl \
		geom/material.h \
		math/ray.h \
		geom/triangle.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o edge.o geom/edge.cpp

vertex.o: geom/vertex.cpp geom/vertex.h \
		geom/edge.h \
		geom/polygon.h \
		math/CS123Algebra.h \
		math/CS123Matrix.h \
		math/CS123Vector.h \
		lib/CS123Common.h \
		math/CS123Vector.inl \
		math/CS123Matrix.inl \
		geom/material.h \
		math/ray.h \
		geom/triangle.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o vertex.o geom/vertex.cpp

mesh.o: geom/mesh.cpp geom/mesh.h \
		geom/polygon.h \
		math/CS123Algebra.h \
		math/CS123Matrix.h \
		math/CS123Vector.h \
		lib/CS123Common.h \
		math/CS123Vector.inl \
		math/CS123Matrix.inl \
		geom/edge.h \
		geom/vertex.h \
		geom/material.h \
		math/ray.h \
		geom/triangle.h \
		lib/utils.h \
		support/camera.h \
		main/glwidget.h \
		support/mainwindow.h \
		support/OrbitingCamera.h \
		math/vector.h \
		support/mouseinput.h \
		tools/manipulator.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mesh.o geom/mesh.cpp

material.o: geom/material.cpp geom/material.h \
		math/CS123Algebra.h \
		math/CS123Matrix.h \
		math/CS123Vector.h \
		lib/CS123Common.h \
		math/CS123Vector.inl \
		math/CS123Matrix.inl
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o material.o geom/material.cpp

ray.o: math/ray.cpp math/ray.h \
		math/CS123Algebra.h \
		math/CS123Matrix.h \
		math/CS123Vector.h \
		lib/CS123Common.h \
		math/CS123Vector.inl \
		math/CS123Matrix.inl \
		lib/utils.h \
		support/camera.h \
		geom/polygon.h \
		geom/edge.h \
		geom/vertex.h \
		geom/material.h \
		geom/triangle.h \
		main/glwidget.h \
		support/mainwindow.h \
		support/OrbitingCamera.h \
		math/vector.h \
		support/mouseinput.h \
		geom/mesh.h \
		tools/manipulator.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ray.o math/ray.cpp

triangle.o: geom/triangle.cpp geom/triangle.h \
		math/ray.h \
		math/CS123Algebra.h \
		math/CS123Matrix.h \
		math/CS123Vector.h \
		lib/CS123Common.h \
		math/CS123Vector.inl \
		math/CS123Matrix.inl
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o triangle.o geom/triangle.cpp

geomInteraction.o: main/geomInteraction.cpp main/glwidget.h \
		support/mainwindow.h \
		support/camera.h \
		math/CS123Algebra.h \
		math/CS123Matrix.h \
		math/CS123Vector.h \
		lib/CS123Common.h \
		math/CS123Vector.inl \
		math/CS123Matrix.inl \
		support/OrbitingCamera.h \
		lib/utils.h \
		geom/polygon.h \
		geom/edge.h \
		geom/vertex.h \
		geom/material.h \
		math/ray.h \
		geom/triangle.h \
		math/vector.h \
		support/mouseinput.h \
		geom/mesh.h \
		tools/manipulator.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o geomInteraction.o main/geomInteraction.cpp

manipulator.o: tools/manipulator.cpp tools/manipulator.h \
		geom/vertex.h \
		geom/edge.h \
		geom/polygon.h \
		math/CS123Algebra.h \
		math/CS123Matrix.h \
		math/CS123Vector.h \
		lib/CS123Common.h \
		math/CS123Vector.inl \
		math/CS123Matrix.inl \
		geom/material.h \
		math/ray.h \
		geom/triangle.h \
		geom/mesh.h \
		main/glwidget.h \
		support/mainwindow.h \
		support/camera.h \
		support/OrbitingCamera.h \
		lib/utils.h \
		math/vector.h \
		support/mouseinput.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o manipulator.o tools/manipulator.cpp

moc_glwidget.o: moc_glwidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_glwidget.o moc_glwidget.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

